package main

import (
	"context"
	"fmt"
	"log"

	"github.com/samcharles93/NellDB"
	"github.com/samcharles93/NellDB/sdk"
)

func main() {
	ctx := context.Background()
	store := nell.NewMemoryStore("vector-node")
	db := sdk.New(store, "vector-node", "embeddings")

	fmt.Println("▸ Initializing vector database")

	// 1. Insert some vector documents
	// In a real application, these vectors would be generated by an embedding model
	// (e.g., text-embedding-ada-002, or a local ONNX model).
	docs := []sdk.Doc{
		{
			sdk.FieldID:     "doc:apple",
			sdk.FieldType:   nell.TypeVector,
			"name":          "Apple",
			"category":      "fruit",
			sdk.FieldVector: []float32{0.9, 0.1, 0.1},
		},
		{
			sdk.FieldID:     "doc:banana",
			sdk.FieldType:   nell.TypeVector,
			"name":          "Banana",
			"category":      "fruit",
			sdk.FieldVector: []float32{0.8, 0.2, 0.1},
		},
		{
			sdk.FieldID:     "doc:dog",
			sdk.FieldType:   nell.TypeVector,
			"name":          "Dog",
			"category":      "animal",
			sdk.FieldVector: []float32{0.1, 0.9, 0.2},
		},
		{
			sdk.FieldID:     "doc:cat",
			sdk.FieldType:   nell.TypeVector,
			"name":          "Cat",
			"category":      "animal",
			sdk.FieldVector: []float32{0.1, 0.8, 0.3},
		},
		{
			sdk.FieldID:     "doc:car",
			sdk.FieldType:   nell.TypeVector,
			"name":          "Car",
			"category":      "vehicle",
			sdk.FieldVector: []float32{0.0, 0.1, 0.9},
		},
	}

	_, err := db.PutMany(ctx, docs)
	if err != nil {
		log.Fatalf("PutMany failed: %v", err)
	}
	fmt.Printf("▸ Inserted %d vector documents\n\n", len(docs))

	// 2. Perform Similarity Searches

	// Query 1: Find something similar to a generic "fruit" vector
	queryFruit := []float32{1.0, 0.0, 0.0}
	fmt.Println("▸ Searching for vector similar to [1.0, 0.0, 0.0] (expected: fruits)")
	results, err := db.SearchSimilar(ctx, queryFruit, 2)
	if err != nil {
		log.Fatalf("Search failed: %v", err)
	}
	for i, res := range results {
		fmt.Printf("  %d. %s (%s)\n", i+1, res["name"], res["category"])
	}

	fmt.Println()

	// Query 2: Find something similar to a generic "animal" vector
	queryAnimal := []float32{0.0, 1.0, 0.0}
	fmt.Println("▸ Searching for vector similar to [0.0, 1.0, 0.0] (expected: animals)")
	results, err = db.SearchSimilar(ctx, queryAnimal, 2)
	if err != nil {
		log.Fatalf("Search failed: %v", err)
	}
	for i, res := range results {
		fmt.Printf("  %d. %s (%s)\n", i+1, res["name"], res["category"])
	}
}
